packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  # Allow install/build scripts for dependencies that require native builds
  - "@nestjs/core"
  - bcrypt
  - sharp
  - unrs-resolver
  - "@apollo/protobufjs"
# Optional: fail installs if a new dependency with scripts appears and isn't approved above.
strictDepBuilds: true
