packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "@scarf/scarf"
  - bcrypt
  - prisma
  - sharp
  - unrs-resolver
  - "@scarf/scarf"

strictDepBuilds: true
